# Generated by Django 4.2.3 on 2023-07-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinica', '0002_alter_mascota_mascodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='masFecNacimiento',
            field=models.DateField(db_comment='Fecha de nacimiento de la mascota'),
        ),
    ]
