# Generated by Django 4.2.3 on 2023-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinica', '0004_alter_elementosubtiporemision_elesubtipremnombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='serTipo',
            field=models.CharField(choices=[('ServicioBasico', 'ServicioBasico'), ('ServicioBienestar', 'ServicioBienestar'), ('Urgencias', 'Urgencias'), ('OtrosServicios', 'OtrosServicios')], db_comment='tipo de servicio', max_length=17),
        ),
    ]
